# Generated by Django 2.1.4 on 2018-12-12 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20181210_2307'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='pic.png', upload_to='profile_pics'),
        ),
    ]
