# Generated by Django 2.1.4 on 2018-12-14 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20181214_1708'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='createdTime',
            field=models.DateTimeField(null=True),
        ),
    ]
