# Generated by Django 2.1.4 on 2018-12-15 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_event_createdtime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='friends',
        ),
    ]
